# Generated by Django 5.0 on 2024-09-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levelstudy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mapel', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('level_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelstudy.levelstudy')),
            ],
            options={
                'verbose_name_plural': 'Mata Pelajaran',
                'unique_together': {('nama_mapel', 'level_study')},
            },
        ),
    ]
