# Generated by Django 5.0 on 2024-09-29 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matapelajaran',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Mata Pelajaran'},
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
