version: '3.8'

services:
  # WSGI Server
  django_app_bimbel_wsgi:
    container_name: django_app_bimbel_wsgi
    build:
      context: .
      dockerfile: Dockerfile
    image: fuatanshori12/bimbel-app
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  # Changed bash to sh
    ports:
      - 8000:8000
    depends_on:
      redis_container:
        condition: service_healthy
      mysql_container:
        condition: service_healthy
      celery_worker:
        condition: service_started
    
    networks:
      bimbel-net:
        ipv4_address: 192.168.1.101
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 12G

  redis_container:
    container_name: redis_container
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - bimbel-net
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit to 0.5 CPU
          memory: 1G    # Limit to 1 GB
  
  mysql_container:
    container_name: mysql_container
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Jakarta
    volumes:
      - db_volume:/var/lib/mysql
    command: --default-time-zone='Asia/Jakarta'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 2s
      retries: 3
    networks:
      - bimbel-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G 

  celery_worker:
    container_name: celery_worker
    image: fuatanshori12/bimbel-app
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "celery -A core worker --loglevel=info" 
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - bimbel-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G 

volumes:
  db_volume:
  portainer_data:
  grafana_data:

networks:
  bimbel-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
