version: '3.8'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  certbot-init:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot -d bimbelbanua.my.id -d www.bimbelbanua.my.id -d db.bimbelbanua.my.id -d www.db.bimbelbanua.my.id --email your-email@example.com --agree-tos --non-interactive
    depends_on:
      - web

  web:
    image: nginx:alpine
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./html:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
