global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django_app_bimbel_wsgi'
    static_configs:
      - targets: ['192.168.1.101:8001']

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['192.168.1.15:8080']