# Generated by Django 5.0 on 2024-09-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_study', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Level Study',
            },
        ),
    ]
