# Generated by Django 5.0 on 2024-09-29 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelstudy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelstudy',
            options={'ordering': ['level_study'], 'verbose_name_plural': 'Level Studies'},
        ),
        migrations.AlterField(
            model_name='levelstudy',
            name='level_study',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
