# Generated by Django 5.0 on 2024-10-27 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelstudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelstudy',
            name='kelas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='levelstudy',
            name='level_study',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='levelstudy',
            unique_together={('kelas', 'level_study')},
        ),
    ]
