# Generated by Django 5.0 on 2024-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modul',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Modul'},
        ),
        migrations.AddField(
            model_name='modul',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
