# Generated by Django 5.0 on 2024-10-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
