# Generated by Django 5.0 on 2024-09-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id_nilai', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nilai', models.CharField(max_length=20)),
                ('predikat', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('lulus', 'lulus'), ('tidak lulus', 'tidak lulus')], max_length=12)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapel.matapelajaran')),
            ],
            options={
                'verbose_name_plural': 'Nilai',
            },
        ),
    ]
