# Generated by Django 5.0 on 2024-10-01 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('no_cert', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tingkat_studi', models.CharField(max_length=100)),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('predikat', models.CharField(max_length=2)),
                ('nilai', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sertifikat',
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id_nilai', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('nilai', models.IntegerField()),
                ('predikat', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('lulus', 'lulus'), ('tidak lulus', 'tidak lulus')], max_length=12)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.matapelajaran')),
            ],
            options={
                'verbose_name_plural': 'Nilai',
            },
        ),
    ]
