# Generated by Django 5.0 on 2024-10-01 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nilai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='nilai_obj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nilai.nilai'),
        ),
    ]
