# Generated by Django 5.0 on 2024-10-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0001_initial'),
        ('nilai', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='level_study',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nilai',
            name='mata_pelajaran_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapel.matapelajaran'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='mata_pelajaran',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
