# Generated by Django 5.0 on 2024-10-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0004_sertifikat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertifikat',
            name='nilai',
            field=models.IntegerField(),
        ),
    ]
