# Generated by Django 5.0 on 2024-10-26 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0005_alter_sertifikat_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
