# Generated by Django 5.0 on 2024-10-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0006_nilai_created_at_alter_sertifikat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
