# Generated by Django 5.0 on 2024-10-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0007_alter_nilai_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilai',
            name='created_at',
        ),
    ]
