# Generated by Django 5.0 on 2024-10-26 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0008_remove_nilai_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
