# Generated by Django 5.0 on 2024-10-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0009_nilai_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nilai',
            old_name='created_at',
            new_name='tanggal_ujian',
        ),
    ]
