# Generated by Django 5.0 on 2024-10-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0010_rename_created_at_nilai_tanggal_ujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='kelas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='kelas',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
