# Generated by Django 5.0 on 2024-10-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id_tarif', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('harga', models.PositiveBigIntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tarif',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diskon',
            fields=[
                ('id_diskon', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('diskon_name', models.CharField(max_length=100)),
                ('diskon_code', models.CharField(db_collation='utf8mb4_bin', max_length=100, unique=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('persentase_diskon', models.SmallIntegerField(help_text='pilih diskon dari 1 sampai 100 akan dihitung sebagai persen')),
                ('kedaluwarsa', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.tarif')),
            ],
            options={
                'verbose_name_plural': 'Diskon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('harga', models.PositiveBigIntegerField(blank=True, null=True)),
                ('transaksi_status', models.CharField(choices=[('pending', 'Belum Dibayar'), ('settlement', 'Telah Dibayar'), ('expire', 'Pembayaran Melebihi Batas Waktu'), ('cancel', 'Pesanan Anda Batalkan'), ('deny', 'Pembayaran Ditolak')], db_index=True, max_length=15)),
                ('va_number', models.CharField(blank=True, max_length=18, null=True)),
                ('layanan_pembayaran', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('qrcode_link', models.TextField(blank=True, null=True)),
                ('deep_link_redirect', models.TextField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tarif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pembayaran.tarif')),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
    ]
