# Generated by Django 5.0 on 2024-10-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='diskon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
