# Generated by Django 5.0 on 2024-10-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0003_transaksi_diskon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='diskon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pembayaran.diskon'),
        ),
    ]
