# Generated by Django 5.0 on 2024-09-29 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0004_rename_is_publis_diskon_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diskon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diskon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
