# Generated by Django 5.0 on 2024-10-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0005_alter_diskon_diskon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='harga_awal',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='harga_terpotong',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
