# Generated by Django 5.0 on 2024-09-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0005_tarif_created_at_tarif_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diskon',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Diskon'},
        ),
        migrations.AlterModelOptions(
            name='tarif',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tarif'},
        ),
    ]
