# Generated by Django 5.0 on 2024-10-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0006_transaksi_harga_awal_transaksi_harga_terpotong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='harga',
            new_name='harga_akhir',
        ),
    ]
