# Generated by Django 5.0 on 2024-10-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0007_rename_harga_transaksi_harga_akhir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarif',
            options={'ordering': ['subject'], 'verbose_name_plural': 'Tarif'},
        ),
    ]
