# Generated by Django 5.0 on 2024-09-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0012_alter_diskon_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='transaksi_status',
            field=models.CharField(choices=[('pending', 'Belum Dibayar'), ('settlement', 'Telah Dibayar'), ('expire', 'Pembayaran Melebihi Batas Waktu'), ('cancel', 'Pesanan Anda Batalkan'), ('deny', 'Pembayaran Ditolak')], db_index=True, max_length=15),
        ),
    ]
