# Generated by Django 5.0 on 2024-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto_profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jenis_kelamin',
            field=models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nomor_telepon',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tanggal_lahir',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tempat_tinggal',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
