# Generated by Django 5.0 on 2024-09-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_foto_alter_profile_jenis_kelamin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_password_reset_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
