# Generated by Django 5.0 on 2024-09-02 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapel', '0001_initial'),
        ('nilai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('no_cert', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('sertifikat', models.ImageField(blank=True, null=True, upload_to='sertifikat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nilai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nilai.nilai')),
            ],
            options={
                'verbose_name_plural': 'Sertifikat',
            },
        ),
        migrations.CreateModel(
            name='SoalUjian',
            fields=[
                ('id_soal', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('gambar_soal', models.ImageField(blank=True, null=True, upload_to='soal', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('soal', models.CharField(max_length=200)),
                ('jawaban_1', models.CharField(blank=True, max_length=200, null=True)),
                ('jawaban_2', models.CharField(blank=True, max_length=200, null=True)),
                ('jawaban_3', models.CharField(max_length=200)),
                ('jawaban_4', models.CharField(max_length=200)),
                ('pilih_jawaban_benar', models.CharField(choices=[('jawaban1', 'jawaban_1'), ('jawaban2', 'jawaban_2'), ('jawaban3', 'jawaban_3'), ('jawaban4', 'jawaban_4')], max_length=200)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.matapelajaran')),
            ],
            options={
                'verbose_name_plural': 'Soal Ujian',
            },
        ),
    ]
