# Generated by Django 5.0 on 2024-10-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soalujian',
            name='jawaban_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soalujian',
            name='jawaban_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soalujian',
            name='jawaban_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soalujian',
            name='jawaban_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soalujian',
            name='jawaban_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soalujian',
            name='pilih_jawaban_benar',
            field=models.CharField(choices=[('jawaban1', 'jawaban_1'), ('jawaban2', 'jawaban_2'), ('jawaban3', 'jawaban_3'), ('jawaban4', 'jawaban_4'), ('jawaban5', 'jawaban_5'), ('jawaban6', 'jawaban_6'), ('jawaban7', 'jawaban_7')], max_length=200),
        ),
    ]
