# Generated by Django 5.0 on 2024-10-01 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertifikat',
            name='no_cert',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
