version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - /home/fuatanshori/etc/letsencrypt:/etc/letsencrypt
       - certbot_www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - /home/fuatanshori/etc/letsencrypt:/etc/letsencrypt 
      - certbot_www:/var/www/certbot    
volumes:
  certbot_www: