version: '3.8'
services: 
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    image: fuatanshori12/nginx-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot