version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ~/letsencrypt:/etc/letsencrypt
       - certbot-data:/var/www/certbot  # Menggunakan volume

  certbot:
    image: certbot/certbot
    volumes:
      - ~/letsencrypt:/etc/letsencrypt 
      - certbot-data:/var/www/certbot  # Menggunakan volume
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-data:  # Mendeklarasikan volume
