version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Mengarahkan port 80 ke host
    volumes:
      - ./certbot:/var/www/certbot  # Memetakan volume untuk Certbot
      - ./letsencrypt:/etc/letsencrypt  # Memetakan volume untuk menyimpan sertifikat
