version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ~/letsencrypt:/etc/letsencrypt
       - certbot-data:/var/www/certbot  # Use a local directory

  certbot:
    image: certbot/certbot
    volumes:
      - ~/letsencrypt:/etc/letsencrypt 
      - certbot-data:/var/www/certbot  # Use a local directory

volumes:
  certbot-data:  # Mendeklarasikan volume