# Generated by Django 5.0 on 2024-10-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimoni', '0002_alter_testimoni_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoni',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
