# Generated by Django 5.0 on 2024-10-29 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimoni', '0003_alter_testimoni_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimoni',
            old_name='created_at',
            new_name='tanggal',
        ),
    ]
